In [1]:
# ============================================================
# Cella 1: Import delle librerie
# Spiegazione: importiamo tutti gli strumenti che useremo.
# Dare un "alias" (pd, np, plt, sns) è convenzione standard.
# ============================================================

import pandas as pd           # per lavorare con tabelle (DataFrame)
import numpy as np            # per calcoli numerici
import matplotlib.pyplot as plt  # per creare grafici
import seaborn as sns          # grafici statistici più belli
import warnings
warnings.filterwarnings('ignore')   # nascondi avvisi non critici

# Impostazioni grafici
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['font.size'] = 12
sns.set_theme(style='whitegrid', palette='husl')

print("Librerie importate con successo!")

Librerie importate con successo!

In [2]:
# ============================================================
# Cella 2: Caricamento del dataset
# pd.read_csv() legge un file CSV e crea un DataFrame.
# Un DataFrame è come una tabella Excel in Python.
# ============================================================

# Prova prima con il file principale, poi con quello expanded se esiste
import os

# Adatta questo nome al file effettivamente scaricato
possible_files = [
    'data/StudentPerformanceFactors.csv'
]

df = None
for path in possible_files:
    if os.path.exists(path):
        df = pd.read_csv(path)
        print(f"Dataset caricato da: {path}")
        break

if df is None:
    print("ATTENZIONE: nessun file trovato. Controlla la cartella data/")
    print("File presenti:", os.listdir('data'))
else:
    print(f"\nDimensioni dataset: {df.shape[0]} righe × {df.shape[1]} colonne")

Dataset caricato da: data/StudentPerformanceFactors.csv

Dimensioni dataset: 6607 righe × 20 colonne

In [3]:
# ============================================================
# Cella 3: Prima occhiata al dataset
# .head() mostra le prime 5 righe (come vedere l'intestazione di Excel)
# ============================================================

print("=== PRIME 5 RIGHE ===")
df.head()  # In Jupyter, l'ultima riga viene visualizzata come tabella

=== PRIME 5 RIGHE ===

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [4]:
# ============================================================
# Cella 4: Informazioni strutturali
# .info() dice: quante righe, che tipo è ogni colonna,
# e quanti valori non-nulli (ovvero: ci sono dati mancanti?)
# ============================================================

print("=== INFORMAZIONI SUL DATASET ===")
df.info()

print("\n=== NOMI DELLE COLONNE ===")
print(df.columns.tolist())

print("\n=== TIPI DI DATI ===")
print(df.dtypes)

=== INFORMAZIONI SUL DATASET ===
<class 'pandas.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   str
 3   Access_to_Resources         6607 non-null   str
 4   Extracurricular_Activities  6607 non-null   str
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   str
 8   Internet_Access             6607 non-null   str
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   str
 11  Teacher_Quality             6529 non-null   str
 12  School_Type                 6607 non-null   str
 13  Peer_Influence              6607 non-null   str
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   str
 16  Parental_Education_Level    6517 non-null   str
 17  Distance_from_Home          6540 non-null   str
 18  Gender                      6607 non-null   str
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), str(13)
memory usage: 1.0 MB

=== NOMI DELLE COLONNE ===
['Hours_Studied', 'Attendance', 'Parental_Involvement', 'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours', 'Previous_Scores', 'Motivation_Level', 'Internet_Access', 'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type', 'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities', 'Parental_Education_Level', 'Distance_from_Home', 'Gender', 'Exam_Score']

=== TIPI DI DATI ===
Hours_Studied                 int64
Attendance                    int64
Parental_Involvement            str
Access_to_Resources             str
Extracurricular_Activities      str
Sleep_Hours                   int64
Previous_Scores               int64
Motivation_Level                str
Internet_Access                 str
Tutoring_Sessions             int64
Family_Income                   str
Teacher_Quality                 str
School_Type                     str
Peer_Influence                  str
Physical_Activity             int64
Learning_Disabilities           str
Parental_Education_Level        str
Distance_from_Home              str
Gender                          str
Exam_Score                    int64
dtype: object

In [5]:
# ============================================================
# Cella 5: Statistiche descrittive
# .describe() calcola: media, deviazione standard, min, max,
# quartili (25%, 50%=mediana, 75%) per le colonne numeriche.
# ============================================================

print("=== STATISTICHE COLONNE NUMERICHE ===")
df.describe().round(2)

=== STATISTICHE COLONNE NUMERICHE ===

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6607.00,6607.00,6607.00,6607.00,6607.00,6607.00,6607.00
mean,19.98,79.98,7.03,75.07,1.49,2.97,67.24
std,5.99,11.55,1.47,14.40,1.23,1.03,3.89
min,1.00,60.00,4.00,50.00,0.00,0.00,55.00
25%,16.00,70.00,6.00,63.00,1.00,2.00,65.00
50%,20.00,80.00,7.00,75.00,1.00,3.00,67.00
75%,24.00,90.00,8.00,88.00,2.00,4.00,69.00
max,44.00,100.00,10.00,100.00,8.00,6.00,101.00

In [6]:
# ============================================================
# Cella 6: Analisi dei valori mancanti (NaN = Not a Number)
# In ogni dataset reale ci sono dati mancanti. Dobbiamo
# sapere quanti ce ne sono e in quali colonne.
# ============================================================

missing = df.isnull().sum()
missing_perc = (missing / len(df) * 100).round(2)

missing_df = pd.DataFrame({
    'Valori mancanti': missing,
    'Percentuale %': missing_perc
}).sort_values('Valori mancanti', ascending=False)

print("=== VALORI MANCANTI PER COLONNA ===")
print(missing_df[missing_df['Valori mancanti'] > 0])

if missing.sum() == 0:
    print("Nessun valore mancante! Il dataset è completo.")
else:
    print(f"\nTotale valori mancanti: {missing.sum()}")

=== VALORI MANCANTI PER COLONNA ===
                          Valori mancanti  Percentuale %
Parental_Education_Level               90           1.36
Teacher_Quality                        78           1.18
Distance_from_Home                     67           1.01

Totale valori mancanti: 235

In [7]:
# ============================================================
# Cella 7: Pulizia del dataset
# Strategia: eliminiamo TUTTE le righe che contengono
# almeno un valore mancante (NaN), in qualsiasi colonna.
# ============================================================

df_clean = df.copy()  # lavoriamo sempre su una copia

righe_prima = len(df_clean)

df_clean = df_clean.dropna()  # elimina ogni riga con almeno un NaN

righe_dopo = len(df_clean)
righe_eliminate = righe_prima - righe_dopo

print(f"Righe prima della pulizia:    {righe_prima}")
print(f"Righe eliminate (con NaN):    {righe_eliminate} ({righe_eliminate/righe_prima*100:.1f}%)")
print(f"Righe dopo la pulizia:        {righe_dopo}")
print(f"Valori mancanti rimasti:      {df_clean.isnull().sum().sum()}")

Righe prima della pulizia:    6607
Righe eliminate (con NaN):    229 (3.5%)
Righe dopo la pulizia:        6378
Valori mancanti rimasti:      0